# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: windows-2022

#variables:
#- template: Env-variables/env-dev.yml

steps:
- task: winvision-bv.winvisionbv-cosmosdb-tasks.CosmosDBCollectionManagement.CosmosDBCollectionManagement@1
  displayName: 'Cosmos DB Collection Management: Create collection'
  inputs:
    #actionType: Delete  #Update or Delete
    cosmosDBConnectionstring: 'AccountEndpoint=https://devtes.documents.azure.com:443/;AccountKey=id1ajWZvKbfQswqRcvjmhCuFXD6a6xYFaqNZafOvoMq2sBDgzMIes8sLQW0VWqGBLqxfIkgrjOrpKW114qOeDA==;Database=devtesdb'
    cosmosDBCollection: 'container'
    cosmosDBCollectionThroughput: 500
    cosmosDBPartitionKey: /employeeId
    cosmosDBTimeToLive: 1
    #cosmosDBIndexingPolicyType: filePath
    #cosmosDBIndexingPolicyFile: '$(System.DefaultWorkingDirectory)/_sdfdsfsfd_Cosmos-db/cosmos-import-export.json'
    cosmosDBIndexingPolicy: |
     {
        "indexingMode": "consistent",
        "automatic": true,
        "includedPaths": [
         {
            "path": "/aanaa*",
            "indexes": [
                {
                    "kind": "Range",
                    "dataType": "Number",
                    "precision": -1
                },
                {
                    "kind": "Range",
                    "dataType": "String",
                    "precision": -1
                }
            ]
        }
      ],
     "excludedPaths": [
        {
            "path": "/\"_etag\"/?"
        }
       ] }